quiz/ques/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /ques/
    url(r'^$', views.index, name='index'),
    # ex: /ques/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/mod$', views.modify, name='modify'),
    url(r'^(?P<question_id>[0-9]+)/modify$', views.changes, name='changes'),
    # ex: /ques/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /ques/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^add/$', views.add, name='add'),
    # ex: /ques/3/?choice=5
    # r'^blog/page(?P<num>[0-9]+)/$'
    # url(r'^(?P<question_id>[0-9]+)/?choice=(?P<_id>[0-9]+)/$',
    # views.response, name='response'),
]

quiz/quiz/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'quiz.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'^ques/', include('ques.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       )

quiz/ques/models.py
from django.db import models

# Create your models here.


class questions(models.Model):
    question = models.CharField(max_length=1000)
    qid = models.IntegerField(primary_key=True)

    def __str__(self):
        return self.question


class answer(models.Model):
    qid = models.ForeignKey(questions, default=0)
    ansid = models.IntegerField()

    def __str__(self):
        return self.ansid


class choice(models.Model):
    cid = models.IntegerField(primary_key=True)
    qid = models.ForeignKey(questions)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

quiz/ques/forms.py
from django import forms
from django.db import connection
from .models import choice
# from .models import questions


class OptionsForm(forms.Form):
    # print()
    # cursor = connection.cursor()
    # cursor.execute(
    #     "select choice_text, choice_text from ques_choice where qid_id = 1")
    # CHOICES = cursor.fetchall()
    q = choice.objects.get(pk=question_id)
    ans = forms.ChoiceField(choices=q)

quiz/ques/views.py
from django.http import Http404
from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from .models import questions, answer, choice


def index(request):
    ques_avail = questions.objects.all()
    context = {'ques_avail': ques_avail}
    return render(request, 'ques/index.html', context)


def detail(request, question_id):
    # form = OptionsForm(request.POST or None)
    try:
        q = questions.objects.get(pk=question_id)
    except questions.DoesNotExist:
        raise Http404("Question does not exist")
    if request.GET.get('choice') is None:
        return render(request, 'ques/detail.html', {'question': q})
    
    else:
        pop = request.GET['choice']
        obj = answer(qid=q, ansid=int(pop))
        obj.save()
        return render_to_response('ques/answer.html')

def changes(request, question_id):
    return render_to_response('ques/change_choices.html')

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)


def add(request):
    if request.GET.get('question') is None:
        return render_to_response('ques/add.html')
    else:
        if request.GET.get('choice') is not None:
            # TODO: get the next qid for entry in db.
            latest_ques = questions.objects.order_by('qid').last()
            obj = questions(
                question=request.GET['question'], qid=latest_ques.qid+1)
            obj.save()
            # TODO: get cid for choice entry.
            latest_choice = choice.objects.order_by('cid').last()
            choice_obj = choice(
                cid=latest_choice.cid + 1, qid=obj,
                choice_text=request.GET['choice'], votes=0)
            choice_obj.save()
            return render_to_response('ques/add.html')


def modify(request, question_id):
    if request.GET.get('question') is None:
        return render_to_response('ques/modify.html')
    else:
        q = questions.objects.get(pk=question_id)
        q.question = request.GET['question']
        q.save()
        ques_avail = questions.objects.all()
        context = {'ques_avail': ques_avail}
        return render(request, 'ques/index.html', context)

quiz/ques/templates/ques/add.html
<!DOCTYPE html>
<html lang="en">
<head>  
  <title>Quiz</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="../../static/bootstrap/css/bootstrap.min.css">
  <script src="../../static/bootstrap/js/bootstrap.min.js"></script>
</head>

<body>
<form action="">
  <div class="form-group">
    <label for="Input_question">Enter Question:</label>
    <input type="question" class="form-control" id="question" placeholder="Enter Question" name="question">
    <br/>
    <label for="Input_choice">Choice</label>
    <input type="choice" class="form-control" id="choice" placeholder="Enter Choice" name="choice">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
</body>

quiz/ques/templates/ques/answer.html
<!DOCTYPE html>
<html lang="en">
<head>	
	<title>Bootstrap Example</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="../../static/bootstrap/css/bootstrap.min.css">
	<script src="../../static/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
	<p>Submitted.</p>
</body>

quiz/ques/templates/ques/change_choices.html
<!DOCTYPE html>
<html lang="en">
<head>	
	<title>Quiz</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="../../static/bootstrap/css/bootstrap.min.css">
	<script src="../../static/bootstrap/js/bootstrap.min.js"></script>
</head>

<h1>Choices</h1>

quiz/ques/templates/ques/detail.html
<!DOCTYPE html>
<html lang="en">
<head>	
	<title>Quiz</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="../../static/bootstrap/css/bootstrap.min.css">
	<script src="../../static/bootstrap/js/bootstrap.min.js"></script>
</head>

<h1>Question:</h1>
<h2>{{ question.question }}</h2>

{% if question.choice_set.all %}
	<form action="">
		{% for choice in question.choice_set.all %}
		    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.cid }}" />
		    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
		{% endfor %}
		<br>
		<input type="submit" class="btn btn-success btn-large" value="Answer" />
		<br><br>
	</form>
{% else %}
	<p>No options are available. Ttyl</p>
{% endif %}
<form action="{% url 'changes' question.qid %}">
	<input type="submit" name = "modify" class="btn btn-success btn-danger" value="Modify Choices" />
</form>

quiz/ques/templates/ques/header.html
<!DOCTYPE html>
<html lang="en">
<head>	
	<title>Bootstrap Example</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="../static/bootstrap/css/bootstrap.min.css">
	<script src="../static/bootstrap/js/bootstrap.min.js"></script>
</head>

quiz/ques/templates/ques/index.html
<!DOCTYPE html>
<html lang="en">

<head>  
    <title>Quiz</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../../static/bootstrap/css/bootstrap.min.css">
    <script src="../../static/bootstrap/js/bootstrap.min.js"></script>
</head>

{% if ques_avail %}
    <ul>
    {% for q in ques_avail %}
        <br /><h3> <span class="glyphicon glyphicon-asterisk"></span>  <a href="{% url 'detail' q.qid %}" >{{ q.question }}</a></h3>
        <div>
            <a href="{% url 'modify' q.qid %}">
                <input type="submit" class="btn btn-info btn-large" value="Modify Me!" />
            </a>
        </div>
    {% endfor %}
    </ul>
{% else %}
    <p>No questions are available.</p>
{% endif %}
<div align="center">
<a href="{% url 'add'%}">
<input type="submit" class="btn btn-success btn-large" value="Add New Question" /></a>
</div>

quiz/ques/templates/ques/modify.html
<!DOCTYPE html>
<html lang="en">
<head>	
	<title>Quiz</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="../../static/bootstrap/css/bootstrap.min.css">
	<script src="../../static/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
<form action="">
  <div class="form-group">
    <label for="Input_question">Enter Question:</label>
    <input type="question" class="form-control" id="question" placeholder="Enter Question" name="question">
    <br/>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>
</body>

quiz/ques/templates/ques/response.html
<!DOCTYPE html>
<html lang="en">
<head>	
	<title>Quiz</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="../static/bootstrap/css/bootstrap.min.css">
	<script src="../static/bootstrap/js/bootstrap.min.js"></script>
</head>

<h1>Question:</h1>
<p>hii</p>